%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 
% Geometry of vibrating point scatterer with approximation
%
% Point Scatterer:  Point scatterer location in Component coordinates:
%                   X = 0 m, Y = 0 m, Z = 0 m
%
% By H.J. Park
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
clc; close all; clear;

%% Parameters

T = 5;                              % total time duration
Fs = 1e3;                           % simulation sample rate
nt = T*Fs;                          % total number of samples
dt = 1/Fs;                          
t = 0:dt:T-dt;                      % time span
F0 = 5e9;                           % center frequency
c = 299792458;                      
lambda = c/F0;                      % wavelength

Fv = 5;                             % vibrating frequency
Av = 0.05;                          % vibrating displacement
Phiv = 0;                           % vibrating initial phase
Dirv = [1; 0; 0];                   % vibrating direction in Local coordinates
Dirv = Dirv/norm(Dirv);             
R0 = [6; 6; 1];                     % initial position of target
V = [-1; -1; 0];                      % bulk velocity of target
eulerInitDeg = [0; 0; 0];           % initial rotation of target
eulerRateDeg = [0; 0; 0];           % bulk rotation of target
rcs = 0.8;                          % rcs of point scatterer, ideal

runGeometryAnimation = true;        % enable 3-D geometry animation
animationFrameRate = 30;            % display frame rate [frames/s]
animationPlaybackSpeed = 1;         % 1: real time, 2: twice as fast

%% Geometry

% radar position in Radar coordinates
RadarPos = [0; 0; 0];

% target center position in Radar coordinates
RefRadarTrans = [R0(1)+V(1)*t; ...
                 R0(2)+V(2)*t; ...
                 R0(3)+V(3)*t];

% LOS vector from radar to target center
vecLOS = RefRadarTrans - RadarPos;
for k=1:nt  
    distLOS(k) = sqrt(vecLOS(1,k).^2+vecLOS(2,k).^2+vecLOS(3,k).^2);
end
unitLOS = vecLOS./distLOS;

% rotation of target about radar
yawchange = eulerRateDeg(1)*t;
pitchchange = eulerRateDeg(2)*t;
rollchange = eulerRateDeg(3)*t;
yaw = eulerInitDeg(1)+yawchange;
pitch = eulerInitDeg(2)+pitchchange;
roll = eulerInitDeg(3)+rollchange;
LocRefRot = zeros(3,3,nt);
for k=1:nt
    cy = cosd(yaw(k)); sy = sind(yaw(k));
    cp = cosd(pitch(k)); sp = sind(pitch(k));
    cr = cosd(roll(k)); sr = sind(roll(k));
    Rz = [cy, -sy, 0; sy, cy, 0; 0, 0, 1];
    Ry = [cp, 0, sp; 0, 1, 0; -sp, 0, cp];
    Rx = [1, 0, 0; 0, cr, -sr; 0, sr, cr];
    LocRefRot(:,:,k) = Rz*Ry*Rx;
end

%% Far-field approximation

% distance of initial position of target center
r0 = distLOS(1);

% radial velocity of target
vr = V.' * unitLOS;

% projection of rotation matrix and vibration to LOS vector
projection = zeros(1,nt);
for k=1:nt
    projection(k) = ...
        unitLOS(:,k).' * LocRefRot(:,:,k) * Dirv;
end

% far-field approximation range
radialTrans = cumtrapz(t, vr);
vibrationDisplacement = Av*sin(2*pi*Fv*t+Phiv);
radialVibration = projection.*vibrationDisplacement;
rff = r0 + radialTrans + radialVibration;

%% Simulation Scenario

data = zeros(1,nt);

for k=1:nt
    amp(k) = sqrt(rcs);
    PHs = amp(k)*exp(-1j*4*pi*rff(k)/lambda);
    data(k) = PHs;
end

%% Plot results

% Micro-Doppler Signature
x = data;
figure(1)
colormap(jet)
spectrogram(x,kaiser(64,10),60,512,Fs,'centered','yaxis');
clim = get(gca,'CLim');
set(gca,'CLim',clim(2) + [-50 0]);
drawnow

%% Geometry animation

if runGeometryAnimation
    % Reconstruct the actual 3-D point position only for visualization.
    % The far-field signal above still uses the scalar range rff.
    pointOffsetRadar = zeros(3,nt);
    for k = 1:nt
        pointOffsetRadar(:,k) = ...
            LocRefRot(:,:,k)*Dirv*vibrationDisplacement(k);
    end
    PointPosExact = RefRadarTrans + pointOffsetRadar;

    % Equivalent point on the LOS whose radar range is the scalar rff.
    PointPosProjected = RadarPos + unitLOS.*rff;
    radialOffsetRadar = PointPosProjected - RefRadarTrans;
    distanceExact = vecnorm(PointPosExact - RadarPos, 2, 1);
    farFieldError = distanceExact - rff;

    % Render only a subset of the signal samples.
    animationStep = max(1, ...
        round(Fs*animationPlaybackSpeed/animationFrameRate));
    animationIndex = 1:animationStep:nt;
    if animationIndex(end) ~= nt
        animationIndex(end+1) = nt;
    end

    % Full-scene bounds include both the actual and projected points.
    geometryPoints = [RadarPos, RefRadarTrans, ...
        PointPosExact, PointPosProjected];
    geometryMin = min(geometryPoints, [], 2);
    geometryMax = max(geometryPoints, [], 2);
    geometrySpan = geometryMax - geometryMin;
    sceneScale = max(geometrySpan);
    if sceneScale == 0
        sceneScale = 1;
    end
    sceneMargin = 0.10*sceneScale;
    targetAxisLength = 0.08*sceneScale;

    % Target-centered zoom limits make the small vibration visible.
    pointRelative = PointPosExact - RefRadarTrans;
    projectedRelative = PointPosProjected - RefRadarTrans;
    relativePoints = [pointRelative, projectedRelative];
    maxRelativeExtent = max(abs(relativePoints), [], 'all');
    zoomRadius = max([2.0*maxRelativeExtent, 2.0*Av, 0.05]);
    zoomAxisLength = 0.65*zoomRadius;

    geometryFigure = figure( ...
        'Name', 'Far-Field Vibrating Point Geometry', ...
        'Color', 'w', 'Position', [100 100 1500 650]);
    animationLayout = tiledlayout(geometryFigure, 1, 2, ...
        'TileSpacing', 'compact', 'Padding', 'compact');

    %% Full radar-target geometry
    sceneAxes = nexttile(animationLayout, 1);
    hold(sceneAxes, 'on');
    grid(sceneAxes, 'on');
    axis(sceneAxes, 'equal');
    view(sceneAxes, 35, 25);
    xlabel(sceneAxes, 'Radar X [m]');
    ylabel(sceneAxes, 'Radar Y [m]');
    zlabel(sceneAxes, 'Radar Z [m]');
    xlim(sceneAxes, ...
        [geometryMin(1)-sceneMargin, geometryMax(1)+sceneMargin]);
    ylim(sceneAxes, ...
        [geometryMin(2)-sceneMargin, geometryMax(2)+sceneMargin]);
    zlim(sceneAxes, ...
        [geometryMin(3)-sceneMargin, geometryMax(3)+sceneMargin]);

    radarHandle = plot3(sceneAxes, RadarPos(1), RadarPos(2), RadarPos(3), ...
        'kp', 'MarkerFaceColor', [1.0 0.8 0.1], 'MarkerSize', 13, ...
        'DisplayName', 'Radar');
    centerPathHandle = plot3(sceneAxes, RefRadarTrans(1,:), ...
        RefRadarTrans(2,:), RefRadarTrans(3,:), 'k--', 'LineWidth', 1.0, ...
        'DisplayName', 'Target-center path');
    centerHandle = plot3(sceneAxes, RefRadarTrans(1,1), ...
        RefRadarTrans(2,1), RefRadarTrans(3,1), 'ko', ...
        'MarkerFaceColor', [0.2 0.7 0.9], 'MarkerSize', 8, ...
        'DisplayName', 'Target center');
    pointHandle = plot3(sceneAxes, PointPosExact(1,1), ...
        PointPosExact(2,1), PointPosExact(3,1), 'ro', ...
        'MarkerFaceColor', 'r', 'MarkerSize', 8, ...
        'DisplayName', 'Actual 3-D point');
    projectedHandle = plot3(sceneAxes, PointPosProjected(1,1), ...
        PointPosProjected(2,1), PointPosProjected(3,1), 'md', ...
        'MarkerFaceColor', 'm', 'MarkerSize', 8, ...
        'DisplayName', 'LOS-projected point');
    actualTraceHandle = plot3(sceneAxes, PointPosExact(1,:), ...
        PointPosExact(2,:), PointPosExact(3,:), ...
        'Color', [0.85 0.2 0.2], 'LineWidth', 1.2, ...
        'DisplayName', 'Actual trajectory');
    projectedTraceHandle = plot3(sceneAxes, PointPosProjected(1,:), ...
        PointPosProjected(2,:), PointPosProjected(3,:), ...
        'Color', [0.65 0.1 0.75], 'LineStyle', '--', 'LineWidth', 1.2, ...
        'DisplayName', 'Projected trajectory');
    losHandle = plot3(sceneAxes, [RadarPos(1), RefRadarTrans(1,1)], ...
        [RadarPos(2), RefRadarTrans(2,1)], ...
        [RadarPos(3), RefRadarTrans(3,1)], 'm-', 'LineWidth', 1.0, ...
        'DisplayName', 'Center LOS');
    vibrationHandle = plot3(sceneAxes, ...
        [RefRadarTrans(1,1), PointPosExact(1,1)], ...
        [RefRadarTrans(2,1), PointPosExact(2,1)], ...
        [RefRadarTrans(3,1), PointPosExact(3,1)], ...
        'c-', 'LineWidth', 2.0, 'DisplayName', '3-D vibration');
    projectionHandle = plot3(sceneAxes, ...
        [RefRadarTrans(1,1), PointPosProjected(1,1)], ...
        [RefRadarTrans(2,1), PointPosProjected(2,1)], ...
        [RefRadarTrans(3,1), PointPosProjected(3,1)], ...
        'g-', 'LineWidth', 2.0, 'DisplayName', 'Radial projection');
    rejectedHandle = plot3(sceneAxes, ...
        [PointPosProjected(1,1), PointPosExact(1,1)], ...
        [PointPosProjected(2,1), PointPosExact(2,1)], ...
        [PointPosProjected(3,1), PointPosExact(3,1)], ...
        'k:', 'LineWidth', 1.4, 'DisplayName', 'Transverse component');

    initialCenter = RefRadarTrans(:,1);
    initialRotation = LocRefRot(:,:,1);
    targetXAxis = quiver3(sceneAxes, initialCenter(1), initialCenter(2), ...
        initialCenter(3), targetAxisLength*initialRotation(1,1), ...
        targetAxisLength*initialRotation(2,1), ...
        targetAxisLength*initialRotation(3,1), 0, 'r', 'LineWidth', 2.0, ...
        'DisplayName', 'Target X_L');
    targetYAxis = quiver3(sceneAxes, initialCenter(1), initialCenter(2), ...
        initialCenter(3), targetAxisLength*initialRotation(1,2), ...
        targetAxisLength*initialRotation(2,2), ...
        targetAxisLength*initialRotation(3,2), 0, 'g', 'LineWidth', 2.0, ...
        'DisplayName', 'Target Y_L');
    targetZAxis = quiver3(sceneAxes, initialCenter(1), initialCenter(2), ...
        initialCenter(3), targetAxisLength*initialRotation(1,3), ...
        targetAxisLength*initialRotation(2,3), ...
        targetAxisLength*initialRotation(3,3), 0, 'b', 'LineWidth', 2.0, ...
        'DisplayName', 'Target Z_L');

    sceneLegend = legend(sceneAxes, ...
        [radarHandle, centerPathHandle, centerHandle, ...
        pointHandle, projectedHandle, actualTraceHandle, ...
        projectedTraceHandle, losHandle, vibrationHandle, ...
        projectionHandle, rejectedHandle, targetXAxis, targetYAxis, ...
        targetZAxis], 'Location', 'northeast');
    sceneLegend.AutoUpdate = 'off';

    %% Target-centered far-field geometry
    zoomAxes = nexttile(animationLayout, 2);
    hold(zoomAxes, 'on');
    grid(zoomAxes, 'on');
    axis(zoomAxes, 'equal');
    view(zoomAxes, 35, 25);
    xlabel(zoomAxes, 'Relative X_R [m]');
    ylabel(zoomAxes, 'Relative Y_R [m]');
    zlabel(zoomAxes, 'Relative Z_R [m]');
    xlim(zoomAxes, zoomRadius*[-1 1]);
    ylim(zoomAxes, zoomRadius*[-1 1]);
    zlim(zoomAxes, zoomRadius*[-1 1]);
    title(zoomAxes, 'Far-field LOS projection (translation removed)');

    zoomCenterHandle = plot3(zoomAxes, 0, 0, 0, 'ko', ...
        'MarkerFaceColor', [0.2 0.7 0.9], 'MarkerSize', 8, ...
        'DisplayName', 'Target center');
    zoomPointHandle = plot3(zoomAxes, pointRelative(1,1), ...
        pointRelative(2,1), pointRelative(3,1), 'ro', ...
        'MarkerFaceColor', 'r', 'MarkerSize', 8, ...
        'DisplayName', 'Actual 3-D point');
    zoomProjectedHandle = plot3(zoomAxes, projectedRelative(1,1), ...
        projectedRelative(2,1), projectedRelative(3,1), 'md', ...
        'MarkerFaceColor', 'm', 'MarkerSize', 8, ...
        'DisplayName', 'LOS projection');
    zoomActualTrace = plot3(zoomAxes, pointRelative(1,:), ...
        pointRelative(2,:), pointRelative(3,:), ...
        'Color', [0.85 0.2 0.2], 'LineWidth', 1.5, ...
        'DisplayName', 'Actual trajectory');
    zoomProjectedTrace = plot3(zoomAxes, projectedRelative(1,:), ...
        projectedRelative(2,:), projectedRelative(3,:), ...
        'Color', [0.65 0.1 0.75], 'LineStyle', '--', 'LineWidth', 1.5, ...
        'DisplayName', 'Projected trajectory');
    zoomVibrationHandle = plot3(zoomAxes, [0, pointRelative(1,1)], ...
        [0, pointRelative(2,1)], [0, pointRelative(3,1)], ...
        'c-', 'LineWidth', 2.0, 'HandleVisibility', 'off');
    zoomProjectionHandle = plot3(zoomAxes, [0, projectedRelative(1,1)], ...
        [0, projectedRelative(2,1)], [0, projectedRelative(3,1)], ...
        'g-', 'LineWidth', 2.0, 'HandleVisibility', 'off');
    zoomRejectedHandle = plot3(zoomAxes, ...
        [projectedRelative(1,1), pointRelative(1,1)], ...
        [projectedRelative(2,1), pointRelative(2,1)], ...
        [projectedRelative(3,1), pointRelative(3,1)], ...
        'k:', 'LineWidth', 1.4, 'HandleVisibility', 'off');

    zoomXAxis = quiver3(zoomAxes, 0, 0, 0, ...
        zoomAxisLength*initialRotation(1,1), ...
        zoomAxisLength*initialRotation(2,1), ...
        zoomAxisLength*initialRotation(3,1), 0, 'r', 'LineWidth', 2.0, ...
        'DisplayName', 'Target X_L');
    zoomYAxis = quiver3(zoomAxes, 0, 0, 0, ...
        zoomAxisLength*initialRotation(1,2), ...
        zoomAxisLength*initialRotation(2,2), ...
        zoomAxisLength*initialRotation(3,2), 0, 'g', 'LineWidth', 2.0, ...
        'DisplayName', 'Target Y_L');
    zoomZAxis = quiver3(zoomAxes, 0, 0, 0, ...
        zoomAxisLength*initialRotation(1,3), ...
        zoomAxisLength*initialRotation(2,3), ...
        zoomAxisLength*initialRotation(3,3), 0, 'b', 'LineWidth', 2.0, ...
        'DisplayName', 'Target Z_L');

    zoomLegend = legend(zoomAxes, ...
        [zoomCenterHandle, zoomPointHandle, ...
        zoomProjectedHandle, zoomActualTrace, zoomProjectedTrace, ...
        zoomXAxis, zoomYAxis, zoomZAxis], 'Location', 'northeast');
    zoomLegend.AutoUpdate = 'off';

    %% Update animated geometry
    for frameNumber = 1:numel(animationIndex)
        if ~isgraphics(geometryFigure)
            break
        end

        k = animationIndex(frameNumber);
        centerPosition = RefRadarTrans(:,k);
        pointPosition = PointPosExact(:,k);
        projectedPosition = PointPosProjected(:,k);
        relativePosition = pointRelative(:,k);
        relativeProjection = projectedRelative(:,k);
        targetRotation = LocRefRot(:,:,k);

        set(centerHandle, 'XData', centerPosition(1), ...
            'YData', centerPosition(2), 'ZData', centerPosition(3));
        set(pointHandle, 'XData', pointPosition(1), ...
            'YData', pointPosition(2), 'ZData', pointPosition(3));
        set(projectedHandle, 'XData', projectedPosition(1), ...
            'YData', projectedPosition(2), 'ZData', projectedPosition(3));
        set(losHandle, 'XData', [RadarPos(1), centerPosition(1)], ...
            'YData', [RadarPos(2), centerPosition(2)], ...
            'ZData', [RadarPos(3), centerPosition(3)]);
        set(vibrationHandle, 'XData', [centerPosition(1), pointPosition(1)], ...
            'YData', [centerPosition(2), pointPosition(2)], ...
            'ZData', [centerPosition(3), pointPosition(3)]);
        set(projectionHandle, ...
            'XData', [centerPosition(1), projectedPosition(1)], ...
            'YData', [centerPosition(2), projectedPosition(2)], ...
            'ZData', [centerPosition(3), projectedPosition(3)]);
        set(rejectedHandle, ...
            'XData', [projectedPosition(1), pointPosition(1)], ...
            'YData', [projectedPosition(2), pointPosition(2)], ...
            'ZData', [projectedPosition(3), pointPosition(3)]);

        set(targetXAxis, 'XData', centerPosition(1), ...
            'YData', centerPosition(2), 'ZData', centerPosition(3), ...
            'UData', targetAxisLength*targetRotation(1,1), ...
            'VData', targetAxisLength*targetRotation(2,1), ...
            'WData', targetAxisLength*targetRotation(3,1));
        set(targetYAxis, 'XData', centerPosition(1), ...
            'YData', centerPosition(2), 'ZData', centerPosition(3), ...
            'UData', targetAxisLength*targetRotation(1,2), ...
            'VData', targetAxisLength*targetRotation(2,2), ...
            'WData', targetAxisLength*targetRotation(3,2));
        set(targetZAxis, 'XData', centerPosition(1), ...
            'YData', centerPosition(2), 'ZData', centerPosition(3), ...
            'UData', targetAxisLength*targetRotation(1,3), ...
            'VData', targetAxisLength*targetRotation(2,3), ...
            'WData', targetAxisLength*targetRotation(3,3));

        set(zoomPointHandle, 'XData', relativePosition(1), ...
            'YData', relativePosition(2), 'ZData', relativePosition(3));
        set(zoomProjectedHandle, 'XData', relativeProjection(1), ...
            'YData', relativeProjection(2), ...
            'ZData', relativeProjection(3));
        set(zoomVibrationHandle, 'XData', [0, relativePosition(1)], ...
            'YData', [0, relativePosition(2)], ...
            'ZData', [0, relativePosition(3)]);
        set(zoomProjectionHandle, 'XData', [0, relativeProjection(1)], ...
            'YData', [0, relativeProjection(2)], ...
            'ZData', [0, relativeProjection(3)]);
        set(zoomRejectedHandle, ...
            'XData', [relativeProjection(1), relativePosition(1)], ...
            'YData', [relativeProjection(2), relativePosition(2)], ...
            'ZData', [relativeProjection(3), relativePosition(3)]);

        set(zoomXAxis, 'UData', zoomAxisLength*targetRotation(1,1), ...
            'VData', zoomAxisLength*targetRotation(2,1), ...
            'WData', zoomAxisLength*targetRotation(3,1));
        set(zoomYAxis, 'UData', zoomAxisLength*targetRotation(1,2), ...
            'VData', zoomAxisLength*targetRotation(2,2), ...
            'WData', zoomAxisLength*targetRotation(3,2));
        set(zoomZAxis, 'UData', zoomAxisLength*targetRotation(1,3), ...
            'VData', zoomAxisLength*targetRotation(2,3), ...
            'WData', zoomAxisLength*targetRotation(3,3));

        title(sceneAxes, sprintf([ ...
            't = %.3f s, exact = %.6f m, far field = %.6f m, ' ...
            'error = %.3e m'], ...
            t(k), distanceExact(k), rff(k), farFieldError(k)));
        drawnow limitrate;
        pause(1/animationFrameRate);
    end
end
