%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 
% micro-Doppler Signature of human vital motion without approximation
%
% Point Scatterer:  Point scatterer location in Component coordinates:
%                   X = 0 m, Y = 0 m, Z = 0 m
%                   Point scatterer has respiratory motion
%                   Point scatterer has heart rate motion
%
% By H.J. Park
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
clc; clear; close all;

%% Parameters

T = 20;                                 % total time duration
Fs = 50;                               % simulation sample rate
nt = T*Fs;                              % total number of samples
dt = 1/Fs;
t = 0:dt:T-dt;                          % time span
F0 = 5e9;                               % center frequency of CW monostatic radar
c = 299792458; 
lambda = c/F0;                          % wavelength

Fr = 0.25;                              % respiratory rate
Ar = 0.005;                             % respiratory displacement
Phir = 0;                               % respiratory initial phase
Fh = 1.2;                               % heart rate
Ah = 0.0005;                            % heart displacement
Phih = 0;
Dirv = [1; 0; 0];                       % direction of vital motion in Local coordinates
Dirv = Dirv/norm(Dirv);
R0 = [1; 0; 0];                         % initial location of human
V = [0; 0; 0];                          % bulk velocity of human
eulerInitDeg = [0; 0; 0];               % initial rotation of human
eulerRateDeg = [0; 0; 0];               % bulk rotation of human
rcs = 0.8;                              % rcs of human point scatterer, ideal

runGeometryAnimation = true;            % enable 3-D geometry animation
animationFrameRate = 20;                % display frame rate [frames/s]
animationPlaybackSpeed = 2;             % 1: real time, 2: twice as fast

%% Geometry

% radar location in Radar coordinates
RadarPos = [0; 0; 0];

% translation of human center about radar
RefRadarTrans = [R0(1)+V(1)*t; ...
                 R0(2)+V(2)*t; ...
                 R0(3)+V(3)*t];

% rotation of human about radar
yawchange = eulerRateDeg(1)*t;
pitchchange = eulerRateDeg(2)*t;
rollchange = eulerRateDeg(3)*t;
yaw = eulerInitDeg(1)+yawchange;
pitch = eulerInitDeg(2)+pitchchange;
roll = eulerInitDeg(3)+rollchange;
LocRefRot = zeros(3,3,nt);
for k=1:nt
    cy = cosd(yaw(k)); sy = sind(yaw(k));
    cp = cosd(pitch(k)); sp = sind(pitch(k));
    cr = cosd(roll(k)); sr = sind(roll(k));
    Rz = [cy, -sy, 0; sy, cy, 0; 0, 0, 1];
    Ry = [cp, 0, sp; 0, 1, 0; -sp, 0, cp];
    Rx = [1, 0, 0; 0, cr, -sr; 0, sr, cr];
    LocRefRot(:,:,k) = Rz*Ry*Rx;
end

% Translation of component about human center
respirationDisplacement = Ar*sin(2*pi*Fr*t+Phir);
heartDisplacement = Ah*sin(2*pi*Fh*t+Phih);
vitalDisplacement = respirationDisplacement + heartDisplacement;
CompLocTrans = Dirv*vitalDisplacement;

% Rotation of component about human center
cpyaw = 0;
cppitch = 0;
cproll = 0;
cpcy = cosd(cpyaw); cpsy = sind(cpyaw);
cpcp = cosd(cppitch); cpsp = sind(cppitch);
cpcr = cosd(cproll); cpsr = sind(cproll);
cpRz = [cpcy, -cpsy, 0; cpsy, cpcy, 0; 0, 0, 1];
cpRy = [cpcp, 0, cpsp; 0, 1, 0; -cpsp, 0, cpcp];
cpRx = [1, 0, 0; 0, cpcr, -cpsr; 0, cpsr, cpcr];
CompLocRot = cpRz*cpRy*cpRx;

% position of point scatterer in Component coordinates
PointCompPos = [0; 0; 0];

%% Simulation Scenario

data = zeros(1,nt);
PointPos = zeros(3,nt);
r_dist = zeros(3,nt);
distance = zeros(1,nt);
amp = sqrt(rcs);

for k=1:nt
    % position of point scatterer in Radar coordinates
    PointPos(:,k) = RefRadarTrans(:,k) + LocRefRot(:,:,k) * ...
                (CompLocTrans(:,k) + CompLocRot * PointCompPos);
    % distance from radar to point scatterer
    r_dist(:,k) = PointPos(:,k) - RadarPos(:);
    distance(k) = sqrt(r_dist(1,k).^2+r_dist(2,k).^2+r_dist(3,k).^2);
    PHs = amp*exp(-1j*4*pi*distance(k)/lambda);
    data(k) = PHs;
end

%% Plot results

% Micro-Doppler Signature
x = data;
figure(1)
colormap(jet)
spectrogram(x,kaiser(128,10),120,512,Fs,'centered','yaxis');
clim = get(gca,'CLim');
set(gca,'CLim',clim(2) + [-50 0]);
drawnow

%% Geometry animation

if runGeometryAnimation
    % Separate respiration and heartbeat in Radar coordinates for visual
    % inspection. Their sum matches the vital-motion translation above.
    respirationOffsetRadar = zeros(3,nt);
    heartOffsetRadar = zeros(3,nt);
    for k = 1:nt
        vitalDirectionRadar = LocRefRot(:,:,k)*Dirv;
        respirationOffsetRadar(:,k) = ...
            vitalDirectionRadar*respirationDisplacement(k);
        heartOffsetRadar(:,k) = ...
            vitalDirectionRadar*heartDisplacement(k);
    end
    respirationPointPos = RefRadarTrans + respirationOffsetRadar;

    % Render only a subset of the signal samples. The radar signal still
    % uses all samples above.
    animationStep = max(1, ...
        round(Fs*animationPlaybackSpeed/animationFrameRate));
    animationIndex = 1:animationStep:nt;
    if animationIndex(end) ~= nt
        animationIndex(end+1) = nt;
    end

    % Full-scene limits include the radar, human center, and vital point.
    geometryPoints = [RadarPos, RefRadarTrans, PointPos];
    geometryMin = min(geometryPoints, [], 2);
    geometryMax = max(geometryPoints, [], 2);
    geometrySpan = geometryMax - geometryMin;
    sceneScale = max(geometrySpan);
    if sceneScale == 0
        sceneScale = 1;
    end
    sceneMargin = 0.10*sceneScale;
    humanAxisLength = 0.08*sceneScale;
    radarAxisLength = humanAxisLength;

    % Target-centered view is displayed in millimeters so that the much
    % smaller heartbeat motion remains visible.
    respirationRelativeMm = 1e3*respirationOffsetRadar;
    heartRelativeMm = 1e3*heartOffsetRadar;
    vitalRelativeMm = respirationRelativeMm + heartRelativeMm;
    maxRelativeExtentMm = max(abs(vitalRelativeMm), [], 'all');
    zoomRadiusMm = max([2.0*maxRelativeExtentMm, ...
        2.0*(Ar+Ah)*1e3, 1.0]);
    zoomAxisLengthMm = 0.65*zoomRadiusMm;

    geometryFigure = figure('Name', 'Human Vital-Motion Geometry', ...
        'Color', 'w', 'Position', [100 100 1500 650]);
    animationLayout = tiledlayout(geometryFigure, 1, 2, ...
        'TileSpacing', 'compact', 'Padding', 'compact');

    %% Full radar-human geometry
    sceneAxes = nexttile(animationLayout, 1);
    hold(sceneAxes, 'on');
    grid(sceneAxes, 'on');
    axis(sceneAxes, 'equal');
    view(sceneAxes, 35, 25);
    xlabel(sceneAxes, 'Radar X [m]');
    ylabel(sceneAxes, 'Radar Y [m]');
    zlabel(sceneAxes, 'Radar Z [m]');
    xlim(sceneAxes, ...
        [geometryMin(1)-sceneMargin, geometryMax(1)+sceneMargin]);
    ylim(sceneAxes, ...
        [geometryMin(2)-sceneMargin, geometryMax(2)+sceneMargin]);
    zlim(sceneAxes, ...
        [geometryMin(3)-sceneMargin, geometryMax(3)+sceneMargin]);

    radarHandle = plot3(sceneAxes, RadarPos(1), RadarPos(2), RadarPos(3), ...
        'kp', 'MarkerFaceColor', [1.0 0.8 0.1], 'MarkerSize', 13, ...
        'DisplayName', 'Radar');
    centerPathHandle = plot3(sceneAxes, RefRadarTrans(1,:), ...
        RefRadarTrans(2,:), RefRadarTrans(3,:), 'k--', 'LineWidth', 1.0, ...
        'DisplayName', 'Human-center path');
    centerHandle = plot3(sceneAxes, RefRadarTrans(1,1), ...
        RefRadarTrans(2,1), RefRadarTrans(3,1), 'ko', ...
        'MarkerFaceColor', [0.2 0.7 0.9], 'MarkerSize', 8, ...
        'DisplayName', 'Human center');
    vitalPointHandle = plot3(sceneAxes, PointPos(1,1), PointPos(2,1), ...
        PointPos(3,1), 'ro', 'MarkerFaceColor', 'r', 'MarkerSize', 8, ...
        'DisplayName', 'Vital point');
    vitalTraceHandle = plot3(sceneAxes, PointPos(1,:), PointPos(2,:), ...
        PointPos(3,:), 'Color', [0.85 0.2 0.2], 'LineWidth', 1.2, ...
        'DisplayName', 'Vital-point trajectory');
    losHandle = plot3(sceneAxes, [RadarPos(1), PointPos(1,1)], ...
        [RadarPos(2), PointPos(2,1)], [RadarPos(3), PointPos(3,1)], ...
        'm-', 'LineWidth', 1.0, 'DisplayName', 'Radar LOS');
    vitalOffsetHandle = plot3(sceneAxes, ...
        [RefRadarTrans(1,1), PointPos(1,1)], ...
        [RefRadarTrans(2,1), PointPos(2,1)], ...
        [RefRadarTrans(3,1), PointPos(3,1)], ...
        'c-', 'LineWidth', 2.0, 'DisplayName', 'Vital displacement');

    % Static Radar-coordinate axes.
    quiver3(sceneAxes, RadarPos(1), RadarPos(2), RadarPos(3), ...
        radarAxisLength, 0, 0, 0, 'Color', [0.7 0 0], ...
        'LineStyle', ':', 'LineWidth', 1.3, 'HandleVisibility', 'off');
    quiver3(sceneAxes, RadarPos(1), RadarPos(2), RadarPos(3), ...
        0, radarAxisLength, 0, 0, 'Color', [0 0.55 0], ...
        'LineStyle', ':', 'LineWidth', 1.3, 'HandleVisibility', 'off');
    quiver3(sceneAxes, RadarPos(1), RadarPos(2), RadarPos(3), ...
        0, 0, radarAxisLength, 0, 'Color', [0 0.25 0.8], ...
        'LineStyle', ':', 'LineWidth', 1.3, 'HandleVisibility', 'off');
    text(sceneAxes, RadarPos(1)+radarAxisLength, RadarPos(2), RadarPos(3), ...
        'X_R', 'Color', [0.7 0 0]);
    text(sceneAxes, RadarPos(1), RadarPos(2)+radarAxisLength, RadarPos(3), ...
        'Y_R', 'Color', [0 0.55 0]);
    text(sceneAxes, RadarPos(1), RadarPos(2), ...
        RadarPos(3)+radarAxisLength, 'Z_R', 'Color', [0 0.25 0.8]);

    initialCenter = RefRadarTrans(:,1);
    initialRotation = LocRefRot(:,:,1);
    humanXAxis = quiver3(sceneAxes, initialCenter(1), initialCenter(2), ...
        initialCenter(3), humanAxisLength*initialRotation(1,1), ...
        humanAxisLength*initialRotation(2,1), ...
        humanAxisLength*initialRotation(3,1), 0, 'r', 'LineWidth', 2.0, ...
        'DisplayName', 'Human X_L');
    humanYAxis = quiver3(sceneAxes, initialCenter(1), initialCenter(2), ...
        initialCenter(3), humanAxisLength*initialRotation(1,2), ...
        humanAxisLength*initialRotation(2,2), ...
        humanAxisLength*initialRotation(3,2), 0, 'g', 'LineWidth', 2.0, ...
        'DisplayName', 'Human Y_L');
    humanZAxis = quiver3(sceneAxes, initialCenter(1), initialCenter(2), ...
        initialCenter(3), humanAxisLength*initialRotation(1,3), ...
        humanAxisLength*initialRotation(2,3), ...
        humanAxisLength*initialRotation(3,3), 0, 'b', 'LineWidth', 2.0, ...
        'DisplayName', 'Human Z_L');

    sceneLegend = legend(sceneAxes, ...
        [radarHandle, centerPathHandle, centerHandle, vitalPointHandle, ...
        vitalTraceHandle, losHandle, vitalOffsetHandle, ...
        humanXAxis, humanYAxis, humanZAxis], 'Location', 'northeast');
    sceneLegend.AutoUpdate = 'off';

    %% Human-centered respiration and heartbeat view
    zoomAxes = nexttile(animationLayout, 2);
    hold(zoomAxes, 'on');
    grid(zoomAxes, 'on');
    axis(zoomAxes, 'equal');
    view(zoomAxes, 35, 25);
    xlabel(zoomAxes, 'Relative X_R [mm]');
    ylabel(zoomAxes, 'Relative Y_R [mm]');
    zlabel(zoomAxes, 'Relative Z_R [mm]');
    xlim(zoomAxes, zoomRadiusMm*[-1 1]);
    ylim(zoomAxes, zoomRadiusMm*[-1 1]);
    zlim(zoomAxes, zoomRadiusMm*[-1 1]);
    title(zoomAxes, ...
        'Respiration and heartbeat components (translation removed)');

    zoomCenterHandle = plot3(zoomAxes, 0, 0, 0, 'ko', ...
        'MarkerFaceColor', [0.2 0.7 0.9], 'MarkerSize', 8, ...
        'DisplayName', 'Human center');
    respirationPointHandle = plot3(zoomAxes, ...
        respirationRelativeMm(1,1), respirationRelativeMm(2,1), ...
        respirationRelativeMm(3,1), 'bo', 'MarkerFaceColor', 'b', ...
        'MarkerSize', 7, 'DisplayName', 'Respiration point');
    combinedPointHandle = plot3(zoomAxes, vitalRelativeMm(1,1), ...
        vitalRelativeMm(2,1), vitalRelativeMm(3,1), 'ro', ...
        'MarkerFaceColor', 'r', 'MarkerSize', 8, ...
        'DisplayName', 'Respiration + heartbeat');
    respirationTraceHandle = plot3(zoomAxes, ...
        respirationRelativeMm(1,:), respirationRelativeMm(2,:), ...
        respirationRelativeMm(3,:), 'b--', 'LineWidth', 1.2, ...
        'DisplayName', 'Respiration trajectory');
    combinedTraceHandle = plot3(zoomAxes, vitalRelativeMm(1,:), ...
        vitalRelativeMm(2,:), vitalRelativeMm(3,:), ...
        'Color', [0.85 0.2 0.2], 'LineWidth', 1.5, ...
        'DisplayName', 'Combined trajectory');
    respirationVectorHandle = plot3(zoomAxes, ...
        [0, respirationRelativeMm(1,1)], ...
        [0, respirationRelativeMm(2,1)], ...
        [0, respirationRelativeMm(3,1)], ...
        'b-', 'LineWidth', 2.2, 'HandleVisibility', 'off');
    heartVectorHandle = plot3(zoomAxes, ...
        [respirationRelativeMm(1,1), vitalRelativeMm(1,1)], ...
        [respirationRelativeMm(2,1), vitalRelativeMm(2,1)], ...
        [respirationRelativeMm(3,1), vitalRelativeMm(3,1)], ...
        'm-', 'LineWidth', 2.5, 'DisplayName', 'Heartbeat component');

    zoomXAxis = quiver3(zoomAxes, 0, 0, 0, ...
        zoomAxisLengthMm*initialRotation(1,1), ...
        zoomAxisLengthMm*initialRotation(2,1), ...
        zoomAxisLengthMm*initialRotation(3,1), 0, 'r', 'LineWidth', 1.8, ...
        'DisplayName', 'Human X_L');
    zoomYAxis = quiver3(zoomAxes, 0, 0, 0, ...
        zoomAxisLengthMm*initialRotation(1,2), ...
        zoomAxisLengthMm*initialRotation(2,2), ...
        zoomAxisLengthMm*initialRotation(3,2), 0, 'g', 'LineWidth', 1.8, ...
        'DisplayName', 'Human Y_L');
    zoomZAxis = quiver3(zoomAxes, 0, 0, 0, ...
        zoomAxisLengthMm*initialRotation(1,3), ...
        zoomAxisLengthMm*initialRotation(2,3), ...
        zoomAxisLengthMm*initialRotation(3,3), 0, 'b', 'LineWidth', 1.8, ...
        'DisplayName', 'Human Z_L');

    zoomLegend = legend(zoomAxes, ...
        [zoomCenterHandle, respirationPointHandle, combinedPointHandle, ...
        respirationTraceHandle, combinedTraceHandle, heartVectorHandle, ...
        zoomXAxis, zoomYAxis, zoomZAxis], 'Location', 'northeast');
    zoomLegend.AutoUpdate = 'off';

    %% Update animated geometry
    for frameNumber = 1:numel(animationIndex)
        if ~isgraphics(geometryFigure)
            break
        end

        k = animationIndex(frameNumber);
        centerPosition = RefRadarTrans(:,k);
        pointPosition = PointPos(:,k);
        targetRotation = LocRefRot(:,:,k);
        respirationPositionMm = respirationRelativeMm(:,k);
        combinedPositionMm = vitalRelativeMm(:,k);

        set(centerHandle, 'XData', centerPosition(1), ...
            'YData', centerPosition(2), 'ZData', centerPosition(3));
        set(vitalPointHandle, 'XData', pointPosition(1), ...
            'YData', pointPosition(2), 'ZData', pointPosition(3));
        set(losHandle, 'XData', [RadarPos(1), pointPosition(1)], ...
            'YData', [RadarPos(2), pointPosition(2)], ...
            'ZData', [RadarPos(3), pointPosition(3)]);
        set(vitalOffsetHandle, ...
            'XData', [centerPosition(1), pointPosition(1)], ...
            'YData', [centerPosition(2), pointPosition(2)], ...
            'ZData', [centerPosition(3), pointPosition(3)]);

        set(humanXAxis, 'XData', centerPosition(1), ...
            'YData', centerPosition(2), 'ZData', centerPosition(3), ...
            'UData', humanAxisLength*targetRotation(1,1), ...
            'VData', humanAxisLength*targetRotation(2,1), ...
            'WData', humanAxisLength*targetRotation(3,1));
        set(humanYAxis, 'XData', centerPosition(1), ...
            'YData', centerPosition(2), 'ZData', centerPosition(3), ...
            'UData', humanAxisLength*targetRotation(1,2), ...
            'VData', humanAxisLength*targetRotation(2,2), ...
            'WData', humanAxisLength*targetRotation(3,2));
        set(humanZAxis, 'XData', centerPosition(1), ...
            'YData', centerPosition(2), 'ZData', centerPosition(3), ...
            'UData', humanAxisLength*targetRotation(1,3), ...
            'VData', humanAxisLength*targetRotation(2,3), ...
            'WData', humanAxisLength*targetRotation(3,3));

        set(respirationPointHandle, ...
            'XData', respirationPositionMm(1), ...
            'YData', respirationPositionMm(2), ...
            'ZData', respirationPositionMm(3));
        set(combinedPointHandle, 'XData', combinedPositionMm(1), ...
            'YData', combinedPositionMm(2), ...
            'ZData', combinedPositionMm(3));
        set(respirationVectorHandle, ...
            'XData', [0, respirationPositionMm(1)], ...
            'YData', [0, respirationPositionMm(2)], ...
            'ZData', [0, respirationPositionMm(3)]);
        set(heartVectorHandle, ...
            'XData', [respirationPositionMm(1), combinedPositionMm(1)], ...
            'YData', [respirationPositionMm(2), combinedPositionMm(2)], ...
            'ZData', [respirationPositionMm(3), combinedPositionMm(3)]);

        set(zoomXAxis, 'UData', zoomAxisLengthMm*targetRotation(1,1), ...
            'VData', zoomAxisLengthMm*targetRotation(2,1), ...
            'WData', zoomAxisLengthMm*targetRotation(3,1));
        set(zoomYAxis, 'UData', zoomAxisLengthMm*targetRotation(1,2), ...
            'VData', zoomAxisLengthMm*targetRotation(2,2), ...
            'WData', zoomAxisLengthMm*targetRotation(3,2));
        set(zoomZAxis, 'UData', zoomAxisLengthMm*targetRotation(1,3), ...
            'VData', zoomAxisLengthMm*targetRotation(2,3), ...
            'WData', zoomAxisLengthMm*targetRotation(3,3));

        title(sceneAxes, sprintf([ ...
            't = %.2f s, range = %.6f m, respiration = %+.3f mm, ' ...
            'heartbeat = %+.3f mm'], ...
            t(k), distance(k), 1e3*respirationDisplacement(k), ...
            1e3*heartDisplacement(k)));
        drawnow limitrate;
        pause(1/animationFrameRate);
    end
end
