%% Single Rigid Component: Exact and Far-Field Range Comparison
% This geometry-only script preserves the hierarchical point-scattering
% model
%
%   A_p_i(t) = A_T_B(t) * B_T_C(t) * C_T_D(t) * D_p_i
%
% and compares three monostatic range models:
%
%   1. Exact spherical range
%   2. Instantaneous reference-LOS far-field range
%   3. Fixed initial-LOS Chen approximation
%
% The common far-field LOS points from the monostatic radar toward the
% target reference origin. No reflectivity, phase, baseband signal, or
% time-frequency processing is modeled.

clear; close all; clc;

%% 1. Select a built-in single-rigid-component scenario
% Available scenarios:
%   "breathing"       : rigid chest-patch translation
%   "two_blade_rotor" : one rigid rotor containing two blades
scenarioName = "two_blade_rotor";

scenario = createScenario(scenarioName);

% Animation settings. The modeled interval is replayed over
% animation.playbackDuration seconds without changing the physical time.
animation.enabled = true;
animation.maximumFrames = 100;
animation.playbackDuration = 8;
animation.showTrail = true;

%% 2. Evaluate the Radar-Reference-Local-Component hierarchy
time = scenario.time;
numberOfTimes = numel(time);
numberOfPoints = size(scenario.pointPosition_D, 2);

pointPosition_A = zeros(3, numberOfPoints, numberOfTimes);
pointRelativePosition_A = zeros(3, numberOfPoints, numberOfTimes);

exactPointRange = zeros(numberOfPoints, numberOfTimes);
instantaneousFarFieldRange = zeros(numberOfPoints, numberOfTimes);
fixedInitialLosRange = zeros(numberOfPoints, numberOfTimes);

referenceOrigin_A = zeros(3, numberOfTimes);
componentOrigin_A = zeros(3, numberOfTimes);
referenceRange = zeros(1, numberOfTimes);
referenceLineOfSight_A = zeros(3, numberOfTimes);
referenceAzimuth = zeros(1, numberOfTimes);
referenceElevation = zeros(1, numberOfTimes);
targetRadiusToRangeRatio = zeros(1, numberOfTimes);
fixedExpansionRatio = zeros(1, numberOfTimes);

transform_A_B = zeros(4, 4, numberOfTimes);
transform_A_C = zeros(4, 4, numberOfTimes);
transform_A_D = zeros(4, 4, numberOfTimes);

radarPosition_A = scenario.radarPosition_A;
pointPositionHomogeneous_D = [scenario.pointPosition_D; ...
                              ones(1, numberOfPoints)];

initialReferenceOrigin_A = ...
    scenario.referenceOriginFunction(time(1));
initialReferenceVector_A = initialReferenceOrigin_A - radarPosition_A;
initialReferenceRange = norm(initialReferenceVector_A);
assert(initialReferenceRange > 0, ...
       'The target reference origin cannot coincide with the radar.');
initialReferenceLineOfSight_A = ...
    initialReferenceVector_A / initialReferenceRange;

for timeIndex = 1:numberOfTimes
    currentTime = time(timeIndex);

    % A_T_B: B translates with the target reference point and remains
    % parallel to radar frame A, following Chen's reference-frame choice.
    currentReferenceOrigin_A = ...
        scenario.referenceOriginFunction(currentTime);
    currentTransform_A_B = makeTransform(eye(3), ...
                                         currentReferenceOrigin_A);

    % B_T_C: target-local attitude about the shared B/C origin.
    currentRotation_B_C = scenario.localRotationFunction(currentTime);
    currentTransform_B_C = makeTransform(currentRotation_B_C, zeros(3,1));

    % C_T_D: motion of the single rigid component relative to target C.
    currentComponentOrigin_C = ...
        scenario.componentOriginFunction(currentTime);
    currentRotation_C_D = ...
        scenario.componentRotationFunction(currentTime);
    currentTransform_C_D = makeTransform(currentRotation_C_D, ...
                                         currentComponentOrigin_C);

    currentTransform_A_C = currentTransform_A_B * currentTransform_B_C;
    currentTransform_A_D = currentTransform_A_C * currentTransform_C_D;

    currentPointPositionHomogeneous_A = ...
        currentTransform_A_D * pointPositionHomogeneous_D;
    currentPointPosition_A = ...
        currentPointPositionHomogeneous_A(1:3,:);

    % Common instantaneous LOS: radar -> current reference origin.
    currentReferenceVector_A = ...
        currentReferenceOrigin_A - radarPosition_A;
    currentReferenceRange = norm(currentReferenceVector_A);
    assert(currentReferenceRange > 0, ...
           'The target reference origin reached the radar position.');
    currentReferenceLineOfSight_A = ...
        currentReferenceVector_A / currentReferenceRange;

    % Scatterer displacement relative to the reference origin, expressed
    % in radar frame A so that the LOS dot product is frame-consistent.
    currentRelativePosition_A = ...
        currentPointPosition_A - currentReferenceOrigin_A;
    currentRadarToPointVector_A = ...
        currentPointPosition_A - radarPosition_A;

    % 1. Exact Euclidean/spherical range.
    currentExactRange = ...
        sqrt(sum(currentRadarToPointVector_A.^2, 1));

    % 2. First-order expansion about the current reference origin:
    %    R_i ~= R_B + n_B^T r_i.
    currentInstantaneousProjection = ...
        currentReferenceLineOfSight_A.' * currentRelativePosition_A;
    currentInstantaneousFarFieldRange = ...
        currentReferenceRange + currentInstantaneousProjection;

    % 3. Chen-style expansion about the fixed initial reference vector:
    %    R_i ~= R_0 + n_0^T[Delta o_B(t) + r_i(t)].
    currentReferenceDisplacement_A = ...
        currentReferenceOrigin_A - initialReferenceOrigin_A;
    currentFixedExpansionVector_A = ...
        currentReferenceDisplacement_A + currentRelativePosition_A;
    currentFixedInitialLosRange = initialReferenceRange + ...
        initialReferenceLineOfSight_A.' * currentFixedExpansionVector_A;

    pointPosition_A(:,:,timeIndex) = currentPointPosition_A;
    pointRelativePosition_A(:,:,timeIndex) = currentRelativePosition_A;
    exactPointRange(:,timeIndex) = currentExactRange.';
    instantaneousFarFieldRange(:,timeIndex) = ...
        currentInstantaneousFarFieldRange.';
    fixedInitialLosRange(:,timeIndex) = currentFixedInitialLosRange.';

    referenceOrigin_A(:,timeIndex) = currentReferenceOrigin_A;
    componentOrigin_A(:,timeIndex) = currentTransform_A_D(1:3,4);
    referenceRange(timeIndex) = currentReferenceRange;
    referenceLineOfSight_A(:,timeIndex) = ...
        currentReferenceLineOfSight_A;
    referenceAzimuth(timeIndex) = atan2( ...
        currentReferenceLineOfSight_A(2), ...
        currentReferenceLineOfSight_A(1));
    referenceElevation(timeIndex) = atan2( ...
        currentReferenceLineOfSight_A(3), ...
        hypot(currentReferenceLineOfSight_A(1), ...
              currentReferenceLineOfSight_A(2)));

    currentPointRadii = sqrt(sum(currentRelativePosition_A.^2, 1));
    targetRadiusToRangeRatio(timeIndex) = ...
        max(currentPointRadii) / currentReferenceRange;
    currentFixedExpansionRadii = ...
        sqrt(sum(currentFixedExpansionVector_A.^2, 1));
    fixedExpansionRatio(timeIndex) = ...
        max(currentFixedExpansionRadii) / initialReferenceRange;

    transform_A_B(:,:,timeIndex) = currentTransform_A_B;
    transform_A_C(:,:,timeIndex) = currentTransform_A_C;
    transform_A_D(:,:,timeIndex) = currentTransform_A_D;
end

%% 3. Store comparison results
results.scenario = scenario;
results.time = time;
results.transform_A_B = transform_A_B;
results.transform_A_C = transform_A_C;
results.transform_A_D = transform_A_D;
results.referenceOrigin_A = referenceOrigin_A;
results.componentOrigin_A = componentOrigin_A;
results.referenceRange = referenceRange;
results.referenceLineOfSight_A = referenceLineOfSight_A;
results.referenceAzimuth = referenceAzimuth;
results.referenceElevation = referenceElevation;
results.initialReferenceRange = initialReferenceRange;
results.initialReferenceLineOfSight_A = initialReferenceLineOfSight_A;
results.pointPosition_A = pointPosition_A;
results.pointRelativePosition_A = pointRelativePosition_A;
results.exactPointRange = exactPointRange;
results.instantaneousFarFieldRange = instantaneousFarFieldRange;
results.fixedInitialLosRange = fixedInitialLosRange;
results.instantaneousFarFieldError = ...
    instantaneousFarFieldRange - exactPointRange;
results.fixedInitialLosError = fixedInitialLosRange - exactPointRange;
results.targetRadiusToRangeRatio = targetRadiusToRangeRatio;
results.fixedExpansionRatio = fixedExpansionRatio;

%% 4. Validate hierarchy and approximation construction
validation = validateModel(scenario, results);
results.validation = validation;

%% 5. Print a concise numerical comparison
fprintf('============================================================\n');
fprintf('Single rigid component: exact and far-field ranges\n');
fprintf('============================================================\n');
fprintf('Scenario                              : %s\n', ...
        scenario.displayName);
fprintf('Number of component points            : %d\n', numberOfPoints);
fprintf('Initial reference range                : %.9f m\n', ...
        initialReferenceRange);
fprintf('Initial reference LOS azimuth          : %.6f deg\n', ...
        rad2deg(referenceAzimuth(1)));
fprintf('Initial reference LOS elevation        : %.6f deg\n', ...
        rad2deg(referenceElevation(1)));
fprintf('Maximum target-radius/range ratio       : %.6e\n', ...
        max(targetRadiusToRangeRatio));
fprintf('Maximum fixed-expansion/range ratio     : %.6e\n', ...
        max(fixedExpansionRatio));
fprintf('Maximum instantaneous-LOS error         : %.9e m\n', ...
        max(abs(results.instantaneousFarFieldError(:))));
fprintf('Maximum fixed-initial-LOS error         : %.9e m\n', ...
        max(abs(results.fixedInitialLosError(:))));
fprintf('Maximum rigid-distance error            : %.3e m\n', ...
        validation.maximumRigidDistanceError);
fprintf('Maximum expanded-equation error         : %.3e m\n', ...
        validation.maximumExpandedEquationError);

%% 6. Visualize the common LOS, range comparison, and convergence
plotFarFieldGeometry(scenario, results);
plotRangeComparison(scenario, results);
plotFarFieldConvergence(scenario, results);

if animation.enabled
    animateFarFieldComparison(scenario, results, animation);
end

%% Local functions
function scenario = createScenario(scenarioName)
    scenarioName = lower(string(scenarioName));

    switch scenarioName
        case "breathing"
            scenario = createBreathingScenario();
        case "two_blade_rotor"
            scenario = createTwoBladeRotorScenario();
        otherwise
            error(['Unknown scenario "%s". Use "breathing" or ' ...
                   '"two_blade_rotor".'], scenarioName);
    end
end

function scenario = createBreathingScenario()
    scenario.displayName = 'Rigid chest-patch respiration';
    scenario.radarPosition_A = [0; 0; 0];

    scenario.samplingRate = 50;
    observationTime = 12;
    scenario.time = 0:1/scenario.samplingRate:observationTime;

    initialReferenceOrigin_A = [0.5; 0.0; 0.0];
    scenario.referenceOriginFunction = ...
        @(t) initialReferenceOrigin_A + zeros(3,1)*t;
    scenario.localRotationFunction = @(t) eye(3);

    equilibriumComponentOrigin_C = [0; 0; 0];
    breathingDirection_C = [1; 0; 0];
    breathingAmplitude = 5e-3;
    breathingFrequency = 0.25;
    breathingInitialPhase = 0;
    scenario.componentOriginFunction = @(t) ...
        equilibriumComponentOrigin_C + breathingAmplitude * ...
        sin(2*pi*breathingFrequency*t + breathingInitialPhase) * ...
        breathingDirection_C;
    scenario.componentRotationFunction = @(t) eye(3);

    [pointY, pointZ] = meshgrid(linspace(-0.15, 0.15, 3), ...
                                linspace(-0.18, 0.18, 3));
    scenario.pointPosition_D = [zeros(1, numel(pointY)); ...
                                pointY(:).'; pointZ(:).'];
    % Use a corner point so that the neglected cross-range term is visible.
    scenario.observationPointIndex = 9;
    scenario.frameAxisLength = 0.35;
    scenario.errorScale = 1e3;
    scenario.errorUnit = 'mm';
end

function scenario = createTwoBladeRotorScenario()
    scenario.displayName = 'Rigid two-blade rotor';
    scenario.radarPosition_A = [0; 0; 0];

    scenario.samplingRate = 500;
    observationTime = 1;
    scenario.time = 0:1/scenario.samplingRate:observationTime;

    initialReferenceOrigin_A = [10.0; 0.0; 0.0];
    referenceVelocity_A = [1.0; 1.0; 0];
    scenario.referenceOriginFunction = ...
        @(t) initialReferenceOrigin_A + referenceVelocity_A*t;
    scenario.localRotationFunction = @(t) eye(3);
    scenario.componentOriginFunction = @(t) zeros(3,1);

    rotationRate = 25;
    angularRate = 2*pi*rotationRate;
    initialRotorPhase = deg2rad(10);
    scenario.componentRotationFunction = @(t) ...
        rotationAboutAxis([0;0;1], angularRate*t + initialRotorPhase);

    bladeRadii = linspace(0.08, 0.6, 10);
    positiveBladePoints = [bladeRadii; ...
                           zeros(size(bladeRadii)); ...
                           zeros(size(bladeRadii))];
    negativeBladePoints = [-bladeRadii; ...
                           zeros(size(bladeRadii)); ...
                           zeros(size(bladeRadii))];
    scenario.pointPosition_D = [zeros(3,1), ...
                                positiveBladePoints, negativeBladePoints];

    scenario.observationPointIndex = 1 + numel(bladeRadii);
    scenario.frameAxisLength = 0.40;
    scenario.errorScale = 1e3;
    scenario.errorUnit = 'mm';
end

function transform = makeTransform(rotation, translation)
    transform = [rotation, translation(:); 0, 0, 0, 1];
end

function rotation = rotationAboutAxis(axis, angle)
    axis = axis(:) / norm(axis);
    axisSkew = [0, -axis(3), axis(2); ...
                axis(3), 0, -axis(1); ...
                -axis(2), axis(1), 0];
    rotation = eye(3) + sin(angle)*axisSkew + ...
               (1-cos(angle))*(axisSkew*axisSkew);
end

function validation = validateModel(scenario, results)
    numberOfTimes = numel(results.time);
    pointPosition_D = scenario.pointPosition_D;
    initialDistanceMatrix = pairwiseDistances(results.pointPosition_A(:,:,1));

    maximumRigidDistanceError = 0;
    maximumExpandedEquationError = 0;
    maximumRotationMatrixError = 0;

    for timeIndex = 1:numberOfTimes
        currentTime = results.time(timeIndex);
        currentPointPosition_A = results.pointPosition_A(:,:,timeIndex);
        currentDistanceMatrix = pairwiseDistances(currentPointPosition_A);
        maximumRigidDistanceError = max(maximumRigidDistanceError, ...
            max(abs(currentDistanceMatrix(:) - initialDistanceMatrix(:))));

        currentReferenceOrigin_A = ...
            scenario.referenceOriginFunction(currentTime);
        currentRotation_B_C = scenario.localRotationFunction(currentTime);
        currentComponentOrigin_C = ...
            scenario.componentOriginFunction(currentTime);
        currentRotation_C_D = ...
            scenario.componentRotationFunction(currentTime);
        expandedPointPosition_A = currentReferenceOrigin_A + ...
            currentRotation_B_C * (currentComponentOrigin_C + ...
                                   currentRotation_C_D*pointPosition_D);
        currentExpandedError = max(abs( ...
            expandedPointPosition_A(:) - currentPointPosition_A(:)));
        maximumExpandedEquationError = max(maximumExpandedEquationError, ...
                                           currentExpandedError);

        currentRotation_A_D = results.transform_A_D(1:3,1:3,timeIndex);
        maximumRotationMatrixError = max(maximumRotationMatrixError, ...
            norm(currentRotation_A_D.'*currentRotation_A_D-eye(3), 'fro'));
    end

    initialApproximationDifference = max(abs( ...
        results.instantaneousFarFieldRange(:,1) - ...
        results.fixedInitialLosRange(:,1)));
    currentReferenceVector_A = results.referenceOrigin_A - ...
                               scenario.radarPosition_A;
    reconstructedReferenceVector_A = ...
        results.referenceLineOfSight_A .* results.referenceRange;
    maximumLosReconstructionError = max(abs( ...
        currentReferenceVector_A(:)-reconstructedReferenceVector_A(:)));

    assert(all(isfinite(results.exactPointRange(:))) && ...
           all(results.exactPointRange(:) > 0), ...
           'All exact point ranges must be finite and positive.');
    assert(maximumRigidDistanceError < 1e-10, ...
           'The component did not preserve rigid point distances.');
    assert(maximumExpandedEquationError < 1e-12, ...
           'The homogeneous and expanded equations do not agree.');
    assert(maximumRotationMatrixError < 1e-10, ...
           'At least one rotation matrix is not orthonormal.');
    assert(initialApproximationDifference < 1e-12, ...
           'The two far-field expansions must agree at the initial time.');
    assert(maximumLosReconstructionError < 1e-12, ...
           'Reference range and LOS do not reconstruct the range vector.');

    validation.maximumRigidDistanceError = maximumRigidDistanceError;
    validation.maximumExpandedEquationError = maximumExpandedEquationError;
    validation.maximumRotationMatrixError = maximumRotationMatrixError;
    validation.initialApproximationDifference = ...
        initialApproximationDifference;
    validation.maximumLosReconstructionError = ...
        maximumLosReconstructionError;
end

function distanceMatrix = pairwiseDistances(pointPosition)
    numberOfPoints = size(pointPosition, 2);
    distanceMatrix = zeros(numberOfPoints, numberOfPoints);
    for pointIndex = 1:numberOfPoints
        displacement = pointPosition - pointPosition(:,pointIndex);
        distanceMatrix(pointIndex,:) = sqrt(sum(displacement.^2, 1));
    end
end

function plotFarFieldGeometry(scenario, results)
    timeIndex = 1;
    observationPointIndex = scenario.observationPointIndex;
    radarPosition_A = scenario.radarPosition_A;
    referenceOrigin_A = results.referenceOrigin_A(:,timeIndex);
    observedPoint_A = ...
        results.pointPosition_A(:,observationPointIndex,timeIndex);
    referenceLos_A = results.referenceLineOfSight_A(:,timeIndex);
    projectedRange = ...
        results.instantaneousFarFieldRange(observationPointIndex,timeIndex);
    projectedPoint_A = radarPosition_A + projectedRange*referenceLos_A;

    figure('Name', ['Far-Field Geometry: ' scenario.displayName], ...
           'Color', 'w', 'Position', [100 100 1120 760]);
    axesHandle = axes();
    hold(axesHandle, 'on');
    grid(axesHandle, 'on');
    axis(axesHandle, 'equal');

    radarHandle = plot3(axesHandle, radarPosition_A(1), ...
        radarPosition_A(2), radarPosition_A(3), 'kp', ...
        'MarkerSize', 13, 'MarkerFaceColor', 'k');
    referenceHandle = plot3(axesHandle, referenceOrigin_A(1), ...
        referenceOrigin_A(2), referenceOrigin_A(3), 'ro', ...
        'MarkerSize', 9, 'MarkerFaceColor', 'r');
    pointPosition_A = results.pointPosition_A(:,:,timeIndex);
    pointHandle = scatter3(axesHandle, pointPosition_A(1,:), ...
        pointPosition_A(2,:), pointPosition_A(3,:), 38, 'b', 'filled');
    observedPointHandle = scatter3(axesHandle, observedPoint_A(1), ...
        observedPoint_A(2), observedPoint_A(3), 85, [1.00 0.75 0.05], ...
        'filled', 'MarkerEdgeColor', 'k');

    exactRangeHandle = plot3(axesHandle, ...
        [radarPosition_A(1), observedPoint_A(1)], ...
        [radarPosition_A(2), observedPoint_A(2)], ...
        [radarPosition_A(3), observedPoint_A(3)], ...
        '-', 'Color', [0.90 0.25 0.10], 'LineWidth', 1.8);
    farFieldRangeHandle = plot3(axesHandle, ...
        [radarPosition_A(1), projectedPoint_A(1)], ...
        [radarPosition_A(2), projectedPoint_A(2)], ...
        [radarPosition_A(3), projectedPoint_A(3)], ...
        '--', 'Color', [0.45 0.15 0.75], 'LineWidth', 1.8);
    plot3(axesHandle, ...
        [projectedPoint_A(1), observedPoint_A(1)], ...
        [projectedPoint_A(2), observedPoint_A(2)], ...
        [projectedPoint_A(3), observedPoint_A(3)], ...
        ':', 'Color', [0.25 0.55 0.25], 'LineWidth', 1.5, ...
        'HandleVisibility', 'off');

    plotFrame(axesHandle, results.transform_A_B(:,:,timeIndex), ...
        scenario.frameAxisLength, [0.15 0.45 0.95], 'B');
    plotFrame(axesHandle, results.transform_A_C(:,:,timeIndex), ...
        scenario.frameAxisLength, [0.10 0.65 0.25], 'C');
    plotFrame(axesHandle, results.transform_A_D(:,:,timeIndex), ...
        scenario.frameAxisLength, [0.80 0.15 0.75], 'D');

    xlabel(axesHandle, 'Radar X_A [m]');
    ylabel(axesHandle, 'Radar Y_A [m]');
    zlabel(axesHandle, 'Radar Z_A [m]');
    title(axesHandle, [scenario.displayName ...
        ': exact range and common reference LOS projection']);
    view(axesHandle, 35, 24);
    legend(axesHandle, ...
        [radarHandle, referenceHandle, pointHandle, observedPointHandle, ...
         exactRangeHandle, farFieldRangeHandle], ...
        {'Monostatic radar', 'Reference origin', 'Point scatterers', ...
         'Observed point', 'Exact spherical range', ...
         'Far-field projected range'}, 'Location', 'best');

    textPosition_A = observedPoint_A + 0.05*scenario.frameAxisLength*[1;1;1];
    text(axesHandle, textPosition_A(1), textPosition_A(2), ...
        textPosition_A(3), sprintf( ...
        'P_%d\nExact = %.6f m\nFF = %.6f m', ...
        observationPointIndex, ...
        results.exactPointRange(observationPointIndex,timeIndex), ...
        projectedRange), 'BackgroundColor', 'w', ...
        'EdgeColor', [0.55 0.55 0.55], 'Margin', 4);
end

function plotFrame(axesHandle, transform_A_X, axisLength, color, frameName)
    origin = transform_A_X(1:3,4);
    rotation = transform_A_X(1:3,1:3);
    axisNames = 'xyz';
    for axisIndex = 1:3
        axisVector = axisLength*rotation(:,axisIndex);
        quiver3(axesHandle, origin(1), origin(2), origin(3), ...
            axisVector(1), axisVector(2), axisVector(3), 0, ...
            'Color', color, 'LineWidth', 1.4, 'MaxHeadSize', 0.6, ...
            'HandleVisibility', 'off');
        labelPosition = origin + 1.08*axisVector;
        text(axesHandle, labelPosition(1), labelPosition(2), ...
            labelPosition(3), sprintf('%s_%c', frameName, ...
            axisNames(axisIndex)), 'Color', color, 'FontWeight', 'bold');
    end
end

function plotRangeComparison(scenario, results)
    time = results.time;
    pointIndex = scenario.observationPointIndex;
    errorScale = scenario.errorScale;

    figure('Name', ['Far-Field Range Comparison: ' scenario.displayName], ...
           'Color', 'w', 'Position', [150 100 1220 800]);
    layout = tiledlayout(2,2, 'TileSpacing', 'compact', ...
                              'Padding', 'compact');

    rangeAxes = nexttile(layout);
    plot(rangeAxes, time, results.exactPointRange(pointIndex,:), ...
        'k-', 'LineWidth', 2.0, 'DisplayName', 'Exact spherical');
    hold(rangeAxes, 'on');
    plot(rangeAxes, time, ...
        results.instantaneousFarFieldRange(pointIndex,:), ...
        '--', 'Color', [0.45 0.15 0.75], 'LineWidth', 1.5, ...
        'DisplayName', 'Instantaneous reference LOS');
    plot(rangeAxes, time, results.fixedInitialLosRange(pointIndex,:), ...
        ':', 'Color', [0.10 0.55 0.25], 'LineWidth', 1.8, ...
        'DisplayName', 'Fixed initial LOS');
    grid(rangeAxes, 'on');
    xlabel(rangeAxes, 'Time [s]');
    ylabel(rangeAxes, 'Range [m]');
    title(rangeAxes, sprintf('Observed point P_%d', pointIndex));
    legend(rangeAxes, 'Location', 'best');

    pointErrorAxes = nexttile(layout);
    plot(pointErrorAxes, time, errorScale* ...
        results.instantaneousFarFieldError(pointIndex,:), ...
        '--', 'Color', [0.45 0.15 0.75], 'LineWidth', 1.6, ...
        'DisplayName', 'Instantaneous LOS - exact');
    hold(pointErrorAxes, 'on');
    plot(pointErrorAxes, time, errorScale* ...
        results.fixedInitialLosError(pointIndex,:), ...
        ':', 'Color', [0.10 0.55 0.25], 'LineWidth', 1.8, ...
        'DisplayName', 'Fixed LOS - exact');
    yline(pointErrorAxes, 0, 'k-', 'HandleVisibility', 'off');
    grid(pointErrorAxes, 'on');
    xlabel(pointErrorAxes, 'Time [s]');
    ylabel(pointErrorAxes, ...
        ['Approximation error [' scenario.errorUnit ']']);
    title(pointErrorAxes, 'Signed range error of the observed point');
    legend(pointErrorAxes, 'Location', 'best');

    maximumErrorAxes = nexttile(layout);
    plot(maximumErrorAxes, time, errorScale*max(abs( ...
        results.instantaneousFarFieldError), [], 1), ...
        '--', 'Color', [0.45 0.15 0.75], 'LineWidth', 1.6, ...
        'DisplayName', 'Instantaneous LOS');
    hold(maximumErrorAxes, 'on');
    plot(maximumErrorAxes, time, errorScale*max(abs( ...
        results.fixedInitialLosError), [], 1), ...
        ':', 'Color', [0.10 0.55 0.25], 'LineWidth', 1.8, ...
        'DisplayName', 'Fixed initial LOS');
    grid(maximumErrorAxes, 'on');
    xlabel(maximumErrorAxes, 'Time [s]');
    ylabel(maximumErrorAxes, ...
        ['Maximum absolute error [' scenario.errorUnit ']']);
    title(maximumErrorAxes, 'Maximum error over all scatterers');
    legend(maximumErrorAxes, 'Location', 'best');

    conditionAxes = nexttile(layout);
    semilogy(conditionAxes, time, results.targetRadiusToRangeRatio, ...
        'b-', 'LineWidth', 1.7, ...
        'DisplayName', 'Target radius / current range');
    hold(conditionAxes, 'on');
    semilogy(conditionAxes, time, results.fixedExpansionRatio, ...
        'r--', 'LineWidth', 1.5, ...
        'DisplayName', 'Fixed expansion / initial range');
    conditionMaximum = max([results.targetRadiusToRangeRatio, ...
                            results.fixedExpansionRatio]);
    ylim(conditionAxes, [1e-4, max(1, 2*conditionMaximum)]);
    grid(conditionAxes, 'on');
    xlabel(conditionAxes, 'Time [s]');
    ylabel(conditionAxes, 'Dimensionless ratio');
    title(conditionAxes, 'Far-field small-parameter checks');
    legend(conditionAxes, 'Location', 'best');

    title(layout, [scenario.displayName ...
        ': exact versus far-field monostatic ranges']);
end

function plotFarFieldConvergence(scenario, results)
    timeIndex = 1;
    relativePointPosition_A = ...
        results.pointRelativePosition_A(:,:,timeIndex);
    targetRadius = max(sqrt(sum(relativePointPosition_A.^2, 1)));
    referenceLos_A = results.initialReferenceLineOfSight_A;

    distanceToSizeRatio = logspace(log10(2), 4, 140);
    testReferenceRange = targetRadius*distanceToSizeRatio;
    maximumFirstOrderError = zeros(size(testReferenceRange));

    projection = referenceLos_A.'*relativePointPosition_A;

    for rangeIndex = 1:numel(testReferenceRange)
        currentReferenceRange = testReferenceRange(rangeIndex);
        radarToPointVector_A = currentReferenceRange*referenceLos_A + ...
                               relativePointPosition_A;
        exactRange = sqrt(sum(radarToPointVector_A.^2, 1));
        firstOrderRange = currentReferenceRange + projection;
        maximumFirstOrderError(rangeIndex) = ...
            max(abs(firstOrderRange-exactRange));
    end

    figure('Name', ['Far-Field Convergence: ' scenario.displayName], ...
           'Color', 'w', 'Position', [220 140 920 650]);
    loglog(distanceToSizeRatio, maximumFirstOrderError, ...
        'Color', [0.45 0.15 0.75], 'LineWidth', 2.0, ...
        'DisplayName', 'First-order LOS projection');
    grid on;
    xlabel('Reference range / target radius');
    ylabel('Maximum absolute range error [m]');
    title([scenario.displayName ...
        ': convergence toward the exact spherical range']);
    legend('Location', 'southwest');
end

function animateFarFieldComparison(scenario, results, animation)
    numberOfTimes = numel(results.time);
    numberOfAnimationFrames = min(animation.maximumFrames, numberOfTimes);
    animationIndices = unique(round(linspace(1, numberOfTimes, ...
                                             numberOfAnimationFrames)));
    numberOfAnimationFrames = numel(animationIndices);

    if numberOfAnimationFrames > 1
        framePause = animation.playbackDuration / ...
                     (numberOfAnimationFrames - 1);
    else
        framePause = 0;
    end

    observationPointIndex = scenario.observationPointIndex;
    radarPosition_A = scenario.radarPosition_A;
    initialLineOfSight_A = results.initialReferenceLineOfSight_A;

    instantaneousProjectedPoint_A = radarPosition_A + ...
        results.referenceLineOfSight_A .* ...
        results.instantaneousFarFieldRange(observationPointIndex,:);
    fixedProjectedPoint_A = radarPosition_A + ...
        initialLineOfSight_A * ...
        results.fixedInitialLosRange(observationPointIndex,:);

    %% 1. Exact spherical range with the target/component close-up
    exactFigure = figure('Name', ...
        ['Animated Exact Spherical Range: ' scenario.displayName], ...
        'Color', 'w', 'Position', [40 120 1450 680]);
    exactLayout = tiledlayout(exactFigure, 1, 2, ...
        'TileSpacing', 'compact', 'Padding', 'compact');
    exactAxes = nexttile(exactLayout, 1);
    exactGeometry = createRangeGeometryAnimation(exactAxes, scenario, ...
        results, 'Exact spherical range', [0.90 0.25 0.10], '-', []);
    closeAxes = nexttile(exactLayout, 2);
    closeGeometry = createComponentCloseUp(closeAxes, scenario, results);

    %% 2. Instantaneous reference-LOS far-field range
    instantaneousFigure = figure('Name', ...
        ['Animated Instantaneous LOS Range: ' scenario.displayName], ...
        'Color', 'w', 'Position', [100 150 1050 720]);
    instantaneousAxes = axes(instantaneousFigure);
    instantaneousGeometry = createRangeGeometryAnimation( ...
        instantaneousAxes, scenario, results, ...
        'Instantaneous reference-LOS range', [0.45 0.15 0.75], '--', ...
        instantaneousProjectedPoint_A);

    %% 3. Fixed initial-LOS Chen approximation
    fixedFigure = figure('Name', ...
        ['Animated Fixed Initial LOS Range: ' scenario.displayName], ...
        'Color', 'w', 'Position', [160 180 1050 720]);
    fixedAxes = axes(fixedFigure);
    fixedGeometry = createRangeGeometryAnimation(fixedAxes, scenario, ...
        results, 'Fixed initial-LOS range', [0.10 0.55 0.25], ':', ...
        fixedProjectedPoint_A);

    %% Animation loop
    for frameIndex = 1:numberOfAnimationFrames
        timeIndex = animationIndices(frameIndex);
        currentTime = results.time(timeIndex);
        currentReferenceOrigin_A = results.referenceOrigin_A(:,timeIndex);
        currentComponentOrigin_A = results.componentOrigin_A(:,timeIndex);
        currentPointPosition_A = results.pointPosition_A(:,:,timeIndex);
        currentObservedPoint_A = ...
            currentPointPosition_A(:,observationPointIndex);
        currentInstantaneousProjectedPoint_A = ...
            instantaneousProjectedPoint_A(:,timeIndex);
        currentFixedProjectedPoint_A = fixedProjectedPoint_A(:,timeIndex);

        updateRangeGeometryAnimation(exactGeometry, ...
            currentReferenceOrigin_A, currentComponentOrigin_A, ...
            currentPointPosition_A, currentObservedPoint_A, []);
        updateRangeGeometryAnimation(instantaneousGeometry, ...
            currentReferenceOrigin_A, currentComponentOrigin_A, ...
            currentPointPosition_A, currentObservedPoint_A, ...
            currentInstantaneousProjectedPoint_A);
        updateRangeGeometryAnimation(fixedGeometry, ...
            currentReferenceOrigin_A, currentComponentOrigin_A, ...
            currentPointPosition_A, currentObservedPoint_A, ...
            currentFixedProjectedPoint_A);

        updateComponentCloseUp(closeGeometry, currentReferenceOrigin_A, ...
            currentComponentOrigin_A, currentPointPosition_A, timeIndex, ...
            scenario, results, animation);

        instantaneousError = results.instantaneousFarFieldError( ...
            observationPointIndex,timeIndex);
        fixedError = results.fixedInitialLosError( ...
            observationPointIndex,timeIndex);
        exactRange = results.exactPointRange(observationPointIndex,timeIndex);
        instantaneousRange = results.instantaneousFarFieldRange( ...
            observationPointIndex,timeIndex);
        fixedRange = results.fixedInitialLosRange( ...
            observationPointIndex,timeIndex);

        title(exactAxes, sprintf( ...
            'Exact spherical range = %.6f m', exactRange));
        title(closeAxes, 'Target/component close-up');
        title(exactLayout, sprintf('%s   |   t = %.3f s', ...
            scenario.displayName, currentTime));
        title(instantaneousAxes, sprintf([ ...
            'Instantaneous reference-LOS range   |   t = %.3f s\n' ...
            'Range = %.6f m, error = %.3e m'], ...
            currentTime, instantaneousRange, instantaneousError));
        title(fixedAxes, sprintf([ ...
            'Fixed initial-LOS range   |   t = %.3f s\n' ...
            'Range = %.6f m, error = %.3e m'], ...
            currentTime, fixedRange, fixedError));

        drawnow;
        if framePause > 0
            pause(framePause);
        end
    end
end

function geometry = createRangeGeometryAnimation(axesHandle, scenario, ...
        results, rangeLabel, rangeColor, rangeLineStyle, projectedPoint_A)
    radarPosition_A = scenario.radarPosition_A;
    hold(axesHandle, 'on');
    grid(axesHandle, 'on');
    axis(axesHandle, 'equal');
    view(axesHandle, 35, 24);

    plot3(axesHandle, radarPosition_A(1), radarPosition_A(2), ...
        radarPosition_A(3), 'kp', 'MarkerSize', 13, ...
        'MarkerFaceColor', 'k', 'DisplayName', 'Monostatic radar');
    geometry.referenceOrigin = plot3(axesHandle, nan, nan, nan, ...
        'ro', 'MarkerSize', 9, 'MarkerFaceColor', 'r', ...
        'DisplayName', 'Reference origin');
    geometry.componentOrigin = plot3(axesHandle, nan, nan, nan, ...
        'md', 'MarkerSize', 9, 'MarkerFaceColor', 'm', ...
        'DisplayName', 'Component origin');
    geometry.points = scatter3(axesHandle, nan, nan, nan, 34, ...
        'b', 'filled', 'DisplayName', 'Current component points');
    geometry.observedPoint = scatter3(axesHandle, nan, nan, nan, 85, ...
        [1.00 0.75 0.05], 'filled', 'MarkerEdgeColor', 'k', ...
        'DisplayName', 'Observed point');
    geometry.referenceLineOfSight = plot3(axesHandle, nan, nan, nan, ...
        'k--', 'LineWidth', 1.1, 'DisplayName', 'Reference LOS');
    geometry.range = plot3(axesHandle, nan, nan, nan, rangeLineStyle, ...
        'Color', rangeColor, 'LineWidth', 1.9, ...
        'DisplayName', rangeLabel);

    geometry.radarPosition_A = radarPosition_A;
    geometry.isApproximation = ~isempty(projectedPoint_A);
    if geometry.isApproximation
        geometry.projection = plot3(axesHandle, nan, nan, nan, 'd', ...
            'Color', rangeColor, 'MarkerSize', 7, ...
            'MarkerFaceColor', 0.55 + 0.45*rangeColor, ...
            'DisplayName', 'Range-equivalent projected point');
        geometry.residual = plot3(axesHandle, nan, nan, nan, ':', ...
            'Color', rangeColor, 'LineWidth', 1.1, ...
            'DisplayName', 'Projection-to-point offset');
        limitData = [radarPosition_A, results.referenceOrigin_A, ...
            results.componentOrigin_A, ...
            reshape(results.pointPosition_A, 3, []), projectedPoint_A];
    else
        limitData = [radarPosition_A, results.referenceOrigin_A, ...
            results.componentOrigin_A, ...
            reshape(results.pointPosition_A, 3, [])];
    end

    xlabel(axesHandle, 'Radar X_A [m]');
    ylabel(axesHandle, 'Radar Y_A [m]');
    zlabel(axesHandle, 'Radar Z_A [m]');
    legend(axesHandle, 'Location', 'best');
    setFixedAxesLimits(axesHandle, limitData, 0.08, 0.15);
end

function updateRangeGeometryAnimation(geometry, referenceOrigin_A, ...
        componentOrigin_A, pointPosition_A, observedPoint_A, projectedPoint_A)
    radarPosition_A = geometry.radarPosition_A;
    set(geometry.referenceOrigin, 'XData', referenceOrigin_A(1), ...
        'YData', referenceOrigin_A(2), 'ZData', referenceOrigin_A(3));
    set(geometry.componentOrigin, 'XData', componentOrigin_A(1), ...
        'YData', componentOrigin_A(2), 'ZData', componentOrigin_A(3));
    set(geometry.points, 'XData', pointPosition_A(1,:), ...
        'YData', pointPosition_A(2,:), 'ZData', pointPosition_A(3,:));
    set(geometry.observedPoint, 'XData', observedPoint_A(1), ...
        'YData', observedPoint_A(2), 'ZData', observedPoint_A(3));
    set(geometry.referenceLineOfSight, ...
        'XData', [radarPosition_A(1), referenceOrigin_A(1)], ...
        'YData', [radarPosition_A(2), referenceOrigin_A(2)], ...
        'ZData', [radarPosition_A(3), referenceOrigin_A(3)]);

    if geometry.isApproximation
        rangeEndpoint_A = projectedPoint_A;
        set(geometry.projection, 'XData', projectedPoint_A(1), ...
            'YData', projectedPoint_A(2), 'ZData', projectedPoint_A(3));
        set(geometry.residual, ...
            'XData', [projectedPoint_A(1), observedPoint_A(1)], ...
            'YData', [projectedPoint_A(2), observedPoint_A(2)], ...
            'ZData', [projectedPoint_A(3), observedPoint_A(3)]);
    else
        rangeEndpoint_A = observedPoint_A;
    end

    set(geometry.range, ...
        'XData', [radarPosition_A(1), rangeEndpoint_A(1)], ...
        'YData', [radarPosition_A(2), rangeEndpoint_A(2)], ...
        'ZData', [radarPosition_A(3), rangeEndpoint_A(3)]);
end

function closeGeometry = createComponentCloseUp(axesHandle, scenario, results)
    radarPosition_A = scenario.radarPosition_A;
    hold(axesHandle, 'on');
    grid(axesHandle, 'on');
    axis(axesHandle, 'equal');
    view(axesHandle, 35, 24);

    initialPointPosition_A = results.pointPosition_A(:,:,1);
    scatter3(axesHandle, initialPointPosition_A(1,:), ...
        initialPointPosition_A(2,:), initialPointPosition_A(3,:), ...
        32, [0.65 0.65 0.65], 'o', ...
        'DisplayName', 'Initial component points');
    closeGeometry.referenceOrigin = plot3(axesHandle, nan, nan, nan, ...
        'ro', 'MarkerSize', 9, 'MarkerFaceColor', 'r', ...
        'DisplayName', 'Reference origin');
    closeGeometry.componentOrigin = plot3(axesHandle, nan, nan, nan, ...
        'md', 'MarkerSize', 9, 'MarkerFaceColor', 'm', ...
        'DisplayName', 'Component origin');
    closeGeometry.points = scatter3(axesHandle, nan, nan, nan, 40, ...
        'b', 'filled', 'DisplayName', 'Current component points');
    closeGeometry.observedPoint = scatter3(axesHandle, nan, nan, nan, 90, ...
        [1.00 0.75 0.05], 'filled', 'MarkerEdgeColor', 'k', ...
        'DisplayName', 'Observed point');
    closeGeometry.trail = plot3(axesHandle, nan, nan, nan, ...
        'Color', [0.35 0.35 0.35], 'LineWidth', 1.0, ...
        'HandleVisibility', 'off');

    closeGeometry.frameB = createAnimatedFrame(axesHandle, ...
        results.transform_A_B(:,:,1), scenario.frameAxisLength, ...
        [0.15 0.45 0.95], 'B');
    closeGeometry.frameC = createAnimatedFrame(axesHandle, ...
        results.transform_A_C(:,:,1), scenario.frameAxisLength, ...
        [0.10 0.65 0.25], 'C');
    closeGeometry.frameD = createAnimatedFrame(axesHandle, ...
        results.transform_A_D(:,:,1), scenario.frameAxisLength, ...
        [0.80 0.15 0.75], 'D');

    initialReferenceOrigin_A = results.referenceOrigin_A(:,1);
    radarDirection_A = radarPosition_A - initialReferenceOrigin_A;
    radarDirection_A = radarDirection_A / norm(radarDirection_A);
    closeGeometry.radarDirectionLength = 0.8*scenario.frameAxisLength;
    closeGeometry.radarDirection = quiver3(axesHandle, ...
        initialReferenceOrigin_A(1), initialReferenceOrigin_A(2), ...
        initialReferenceOrigin_A(3), ...
        closeGeometry.radarDirectionLength*radarDirection_A(1), ...
        closeGeometry.radarDirectionLength*radarDirection_A(2), ...
        closeGeometry.radarDirectionLength*radarDirection_A(3), 0, ...
        'Color', 'k', 'LineStyle', '--', 'LineWidth', 1.2, ...
        'MaxHeadSize', 0.7, 'DisplayName', 'Direction to radar');
    closeGeometry.radarPosition_A = radarPosition_A;

    xlabel(axesHandle, 'Radar X_A [m]');
    ylabel(axesHandle, 'Radar Y_A [m]');
    zlabel(axesHandle, 'Radar Z_A [m]');
    legend(axesHandle, 'Location', 'best');
    closeLimitData = [results.referenceOrigin_A, ...
        results.componentOrigin_A, reshape(results.pointPosition_A, 3, [])];
    setFixedAxesLimits(axesHandle, closeLimitData, 0.18, 0.08);
end

function updateComponentCloseUp(closeGeometry, referenceOrigin_A, ...
        componentOrigin_A, pointPosition_A, timeIndex, ...
        scenario, results, animation)
    observationPointIndex = scenario.observationPointIndex;
    observedPoint_A = pointPosition_A(:,observationPointIndex);
    set(closeGeometry.referenceOrigin, 'XData', referenceOrigin_A(1), ...
        'YData', referenceOrigin_A(2), 'ZData', referenceOrigin_A(3));
    set(closeGeometry.componentOrigin, 'XData', componentOrigin_A(1), ...
        'YData', componentOrigin_A(2), 'ZData', componentOrigin_A(3));
    set(closeGeometry.points, 'XData', pointPosition_A(1,:), ...
        'YData', pointPosition_A(2,:), 'ZData', pointPosition_A(3,:));
    set(closeGeometry.observedPoint, 'XData', observedPoint_A(1), ...
        'YData', observedPoint_A(2), 'ZData', observedPoint_A(3));

    if animation.showTrail
        currentTrail = squeeze(results.pointPosition_A( ...
            :,observationPointIndex,1:timeIndex));
        set(closeGeometry.trail, 'XData', currentTrail(1,:), ...
            'YData', currentTrail(2,:), 'ZData', currentTrail(3,:));
    end

    updateAnimatedFrame(closeGeometry.frameB, ...
        results.transform_A_B(:,:,timeIndex));
    updateAnimatedFrame(closeGeometry.frameC, ...
        results.transform_A_C(:,:,timeIndex));
    updateAnimatedFrame(closeGeometry.frameD, ...
        results.transform_A_D(:,:,timeIndex));

    radarDirection_A = closeGeometry.radarPosition_A - referenceOrigin_A;
    radarDirection_A = radarDirection_A / norm(radarDirection_A);
    directionLength = closeGeometry.radarDirectionLength;
    set(closeGeometry.radarDirection, ...
        'XData', referenceOrigin_A(1), ...
        'YData', referenceOrigin_A(2), ...
        'ZData', referenceOrigin_A(3), ...
        'UData', directionLength*radarDirection_A(1), ...
        'VData', directionLength*radarDirection_A(2), ...
        'WData', directionLength*radarDirection_A(3));
end

function frame = createAnimatedFrame(axesHandle, transform_A_X, ...
                                     axisLength, color, frameName)
    frame.quiver = gobjects(1,3);
    frame.label = gobjects(1,3);
    frame.axisLength = axisLength;

    origin = transform_A_X(1:3,4);
    rotation = transform_A_X(1:3,1:3);
    axisNames = 'xyz';

    for axisIndex = 1:3
        axisVector = axisLength*rotation(:,axisIndex);
        frame.quiver(axisIndex) = quiver3(axesHandle, ...
            origin(1), origin(2), origin(3), ...
            axisVector(1), axisVector(2), axisVector(3), 0, ...
            'Color', color, 'LineWidth', 1.4, 'MaxHeadSize', 0.6, ...
            'HandleVisibility', 'off');

        labelPosition = origin + 1.08*axisVector;
        frame.label(axisIndex) = text(axesHandle, ...
            labelPosition(1), labelPosition(2), labelPosition(3), ...
            sprintf('%s_%c', frameName, axisNames(axisIndex)), ...
            'Color', color, 'FontWeight', 'bold');
    end
end

function updateAnimatedFrame(frame, transform_A_X)
    origin = transform_A_X(1:3,4);
    rotation = transform_A_X(1:3,1:3);

    for axisIndex = 1:3
        axisVector = frame.axisLength*rotation(:,axisIndex);
        set(frame.quiver(axisIndex), ...
            'XData', origin(1), 'YData', origin(2), 'ZData', origin(3), ...
            'UData', axisVector(1), 'VData', axisVector(2), ...
            'WData', axisVector(3));

        labelPosition = origin + 1.08*axisVector;
        set(frame.label(axisIndex), 'Position', labelPosition.');
    end
end

function setFixedAxesLimits(axesHandle, pointData, ...
                            paddingFraction, minimumPadding)
    minimumValues = min(pointData, [], 2);
    maximumValues = max(pointData, [], 2);
    maximumSpan = max(maximumValues - minimumValues);
    padding = max(paddingFraction*maximumSpan, minimumPadding);

    xlim(axesHandle, [minimumValues(1)-padding, maximumValues(1)+padding]);
    ylim(axesHandle, [minimumValues(2)-padding, maximumValues(2)+padding]);
    zlim(axesHandle, [minimumValues(3)-padding, maximumValues(3)+padding]);
end
